---
jobs:
  build:
    docker:
      - image: docker:19.03.8-git
    working_directory: /app
    environment:
      - COMPOSE_FILE: docker-compose.yml:docker-compose.ci.yml
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Installing dependencies
          command: |
            set -x
            apk add --no-cache --no-progress bash py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
            pip install --quiet docker-compose
      - run:
          name: Check if container works
          command: |
            docker-compose up
