---
jobs:
  build:
    docker:
      - image: snymanc/dind:with-docker-compose
    working_directory: /app
    environment:
      - COMPOSE_FILE: docker-compose.yml:docker-compose.ci.yml
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Test my dind image
          command: |
            docker -v
            docker-compose -v
            curl -4 ifconfig.co
